version: '3'

services:
  grafana:
    container_name: grafana-lab
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana
    user: '472'
    command: >
      chown -R root:root /etc/grafana && \
      chmod -R a+r /etc/grafana && \
      chown -R grafana:grafana /var/lib/grafana && \
      chown -R grafana:grafana /usr/share/grafana
    restart: always